server:
  port: 8080

spring:
  application:
    name: reggie_take_out
  #    主从复制之前这样配置数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: abc123
  # 之前上传图片时说大小超过了最大限制，上网搜索后修改了下面两个配置
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  redis:
    host: 8.130.16.137
    port: 6389
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
# 图片路径，在图片的CommonController里面使用
# 修改了图片路径
reggie:
  path: /usr/local/imgs/